name: Validate Container Image

on:
  push:
    branches: ["main"]
    paths:
      - "catalog/**"
      - "ui/**"
      - "catalog.Dockerfile"
      - ".github/workflows/container-validation.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "catalog/**"
      - "ui/**"
      - "catalog.Dockerfile"
      - ".github/workflows/container-validation.yml"

permissions: read-all

jobs:
  build-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

      - name: Build Docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .
          file: ./catalog.Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
